### ISSUE TITLE
Models ending with 'ss' cause failing factory build

### ISSUE THREAD

**Issue by jordanbrock** [stephencelis/minifacture#16]
In my Rails 3.2.8 app I have an "Address" model (which in turn uses an "addresses" table in the DB). When I define a factory for the model as follows

```
Factory.define :address do |f|
  f.name "Address Name %d"
  f.user { Factory(:user) }
  ...
end
```

and then try to create an object using the factory

```
address = Factory.create(:address)
```

it throws this exception:

```
uninitialized constant Addres
...
<edit>/gems/activesupport-3.2.8/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
<edit>/gems/miniskirt-1.2/miniskirt.rb:26:in `build'
<edit>/gems/miniskirt-1.2/miniskirt.rb:39:in `create'
```

I'm presuming this is caused by the 'ss' in the model name.

**Comment by jordanbrock** [comment]
Awesome. Thanks.
